### ISSUE TITLE
fix(): hero on large monitors

### ISSUE THREAD

**Issue by sterlingrules** [sterlingrules/knotwithoutyou#7]
```css
#hero .hero-background canvas {
    object-fit: cover;
    width: 100%;
    height: 100%;
}
```
